import { Product, Category, Corner } from "./types";

export const categories: Category[] = [
  {
    slug: "fresh-daily",
    name: "Fresh & Daily",
    icon: "Apple",
    sections: ["Produce", "Dairy", "Eggs", "Bakery"],
  },
  {
    slug: "smart-deals",
    name: "Smart Deals",
    icon: "Sparkles",
    sections: ["Weekly Specials", "Clearance", "Bulk Savings"],
  },
  {
    slug: "south-asian",
    name: "South Asian Essentials",
    icon: "Star",
    sections: [
      "Lentils & Pulses",
      "Rice & Grains",
      "Spices & Masalas",
      "Flours & Atta",
      "Snacks & Sweets",
      "Oils & Ghee",
    ],
  },
  {
    slug: "ready-to-cook",
    name: "Ready to Cook",
    icon: "ChefHat",
    sections: ["Frozen Meals", "Frozen Veggies", "Frozen Snacks", "Ice Cream"],
  },
  {
    slug: "global-grocers",
    name: "Global Grocers",
    icon: "Globe",
    sections: ["Asian", "Mediterranean", "Latin American", "European"],
  },
  {
    slug: "pantry-staples",
    name: "Pantry Staples",
    icon: "Package",
    sections: ["Canned Goods", "Pasta", "Sauces", "Condiments"],
  },
  {
    slug: "beverages",
    name: "Beverages",
    icon: "Coffee",
    sections: ["Tea & Coffee", "Juices", "Soft Drinks", "Water"],
  },
];

export const corners: Corner[] = [
  {
    slug: "patel-brothers",
    name: "Patel Brothers Corner",
    categorySlug: "south-asian",
    description: "Curated South Asian essentials",
    badge: "Patel Brothers",
    sections: [
      "Lentils & Pulses",
      "Rice & Grains",
      "Spices & Masalas",
      "Flours & Atta",
      "Snacks & Sweets",
      "Oils & Ghee",
    ],
  },
  {
    slug: "shoprite",
    name: "ShopRite Corner",
    categorySlug: "fresh-daily",
    description: "Fresh produce and daily essentials",
    badge: "ShopRite",
    sections: ["Produce", "Dairy", "Bakery"],
  },
  {
    slug: "hmart",
    name: "H-Mart Corner",
    categorySlug: "global-grocers",
    description: "Asian specialty items",
    badge: "H-Mart",
    sections: ["Asian"],
  },
];

export const products: Product[] = [
  // Produce (Fresh & Daily)
  {
    id: "p001",
    name: "Bananas (Organic)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 0.99,
    unit: "lb",
    rank: 1,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for smoothies or breakfast bowls",
    aiSubstituteIds: ["p002"],
    description: "Fresh organic bananas, rich in potassium",
  },
  {
    id: "p002",
    name: "Plantains",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "local",
    price: 1.29,
    unit: "lb",
    rank: 2,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Great for frying or baking",
    description: "Fresh plantains for cooking",
  },
  {
    id: "p003",
    name: "Avocados (Hass)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "shoprite",
    price: 1.49,
    unit: "each",
    rank: 3,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Pair with lime and salt for guacamole",
    description: "Ripe Hass avocados",
  },
  {
    id: "p004",
    name: "Red Onions",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 1.99,
    unit: "3 lb bag",
    rank: 4,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Essential for curries and salads",
    description: "Fresh red onions",
  },
  {
    id: "p005",
    name: "Roma Tomatoes",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "shoprite",
    price: 2.49,
    unit: "lb",
    rank: 5,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for sauces and salsas",
    description: "Fresh Roma tomatoes",
  },
  {
    id: "p006",
    name: "Cilantro (Fresh Bunch)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 0.99,
    unit: "bunch",
    rank: 6,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Essential garnish for curries and tacos",
    description: "Fresh cilantro bunch",
  },
  {
    id: "p007",
    name: "English Cucumbers",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 1.99,
    unit: "each",
    rank: 7,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Great for salads and raita",
    description: "Seedless English cucumbers",
  },

  // Frozen (Ready to Cook)
  {
    id: "f001",
    name: "Frozen Peas",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "neomart",
    price: 2.99,
    unit: "16 oz",
    rank: 1,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Add to pulao or fried rice",
    description: "Premium frozen green peas",
  },
  {
    id: "f002",
    name: "Frozen Broccoli Florets",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "neomart",
    price: 3.49,
    unit: "12 oz",
    rank: 2,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Steam and season for quick side dish",
    description: "Fresh-frozen broccoli florets",
  },
  {
    id: "f003",
    name: "French Fries (Crinkle Cut)",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "neomart",
    price: 4.99,
    unit: "2 lb",
    rank: 3,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Bake or air fry until crispy",
    description: "Classic crinkle-cut fries",
  },
  {
    id: "f004",
    name: "Frozen Paratha (Plain)",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 5.99,
    unit: "20 count",
    rank: 4,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Heat and serve with curry or pickle",
    description: "Authentic frozen plain parathas",
  },
  {
    id: "f005",
    name: "Frozen Aloo Paratha",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 6.49,
    unit: "16 count",
    rank: 5,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Serve with yogurt and pickle",
    description: "Potato-stuffed parathas",
  },
  {
    id: "f006",
    name: "Vanilla Ice Cream",
    categorySlug: "ready-to-cook",
    section: "Ice Cream",
    source: "neomart",
    price: 5.99,
    unit: "1.5 qt",
    rank: 6,
    dietaryTags: [],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Top with chocolate sauce or fresh fruit",
    description: "Premium vanilla ice cream",
  },
  {
    id: "f007",
    name: "Mango Kulfi",
    categorySlug: "ready-to-cook",
    section: "Ice Cream",
    source: "patel",
    price: 7.99,
    unit: "12 count",
    rank: 7,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Traditional Indian frozen dessert",
    description: "Authentic mango kulfi bars",
  },
  {
    id: "f008",
    name: "Frozen Corn Kernels",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "neomart",
    price: 2.49,
    unit: "16 oz",
    rank: 8,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Add to soups and salads",
    description: "Sweet frozen corn",
  },
  {
    id: "f009",
    name: "Frozen Spinach (Chopped)",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "neomart",
    price: 3.29,
    unit: "10 oz",
    rank: 9,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Perfect for palak paneer",
    description: "Pre-chopped frozen spinach",
  },
  {
    id: "f010",
    name: "Frozen Mixed Vegetables",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "neomart",
    price: 3.99,
    unit: "24 oz",
    rank: 10,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Quick stir-fry mix",
    description: "Carrots, peas, corn, green beans blend",
  },
  {
    id: "f011",
    name: "Frozen Edamame",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "hmart",
    price: 4.49,
    unit: "12 oz",
    rank: 11,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Steam and sprinkle with sea salt",
    description: "Premium frozen edamame",
  },
  {
    id: "f012",
    name: "Tater Tots",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "neomart",
    price: 3.99,
    unit: "32 oz",
    rank: 12,
    dietaryTags: ["veg"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Crispy oven-baked tots",
    description: "Classic potato tater tots",
  },
  {
    id: "f013",
    name: "Mozzarella Sticks",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "neomart",
    price: 5.99,
    unit: "24 oz",
    rank: 13,
    dietaryTags: [],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Serve with marinara sauce",
    description: "Breaded mozzarella sticks",
  },
  {
    id: "f014",
    name: "Chicken Nuggets",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "neomart",
    price: 6.99,
    unit: "2 lb",
    rank: 14,
    dietaryTags: [],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Kid-friendly quick meal",
    description: "Crispy chicken nuggets",
  },
  {
    id: "f015",
    name: "Frozen Pizza (Margherita)",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "neomart",
    price: 8.99,
    unit: "each",
    rank: 15,
    dietaryTags: ["veg"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Ready in 12 minutes",
    description: "Classic margherita pizza",
  },
  {
    id: "f016",
    name: "Frozen Samosas (Veg)",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel",
    price: 6.99,
    unit: "20 count",
    rank: 16,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Fry or bake until golden",
    description: "Spiced potato samosas",
  },
  {
    id: "f017",
    name: "Chocolate Ice Cream",
    categorySlug: "ready-to-cook",
    section: "Ice Cream",
    source: "neomart",
    price: 5.99,
    unit: "1.5 qt",
    rank: 17,
    dietaryTags: [],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Rich chocolate flavor",
    description: "Premium chocolate ice cream",
  },
  {
    id: "f018",
    name: "Strawberry Ice Cream",
    categorySlug: "ready-to-cook",
    section: "Ice Cream",
    source: "neomart",
    price: 5.99,
    unit: "1.5 qt",
    rank: 18,
    dietaryTags: [],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Made with real strawberries",
    description: "Creamy strawberry ice cream",
  },
  {
    id: "f019",
    name: "Frozen Waffles",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "neomart",
    price: 4.49,
    unit: "24 count",
    rank: 19,
    dietaryTags: ["veg"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Toast and top with syrup",
    description: "Homestyle frozen waffles",
  },
  {
    id: "f020",
    name: "Frozen Paneer Tikka",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 9.99,
    unit: "16 oz",
    rank: 20,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Microwave or pan-fry",
    description: "Marinated paneer tikka",
  },

  // South Asian Essentials
  {
    id: "s001",
    name: "Toor Dal (Split Pigeon Peas)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel",
    price: 4.99,
    unit: "2 lb",
    rank: 1,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Perfect for dal tadka and sambar",
    aiSubstituteIds: ["s002"],
    description: "Premium quality toor dal",
  },
  {
    id: "s002",
    name: "Chana Dal (Split Chickpeas)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel",
    price: 3.99,
    unit: "2 lb",
    rank: 2,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Great for chana dal fry or halwa",
    description: "Premium chana dal",
  },
  {
    id: "s003",
    name: "Moong Dal (Split Mung Beans)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel",
    price: 4.49,
    unit: "2 lb",
    rank: 3,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Light and nutritious dal",
    description: "Yellow moong dal",
  },
  {
    id: "s004",
    name: "Basmati Rice (Aged)",
    categorySlug: "south-asian",
    section: "Rice & Grains",
    source: "patel",
    price: 19.99,
    unit: "10 lb",
    rank: 4,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Perfect for biryani and pulao",
    description: "Premium aged basmati rice",
  },
  {
    id: "s005",
    name: "Turmeric Powder (Haldi)",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel",
    price: 3.99,
    unit: "7 oz",
    rank: 5,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Essential spice for curries",
    description: "Pure turmeric powder",
  },
  {
    id: "s006",
    name: "Cumin Seeds (Jeera)",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel",
    price: 2.99,
    unit: "3.5 oz",
    rank: 6,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Great for tempering dals",
    description: "Whole cumin seeds",
  },
  {
    id: "s007",
    name: "Garam Masala",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel",
    price: 4.49,
    unit: "3.5 oz",
    rank: 7,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Finishing touch for curries",
    description: "Authentic garam masala blend",
  },
  {
    id: "s008",
    name: "Chakki Atta (Whole Wheat Flour)",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel",
    price: 8.99,
    unit: "10 lb",
    rank: 8,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Perfect for rotis and parathas",
    description: "Stone-ground whole wheat flour",
  },
  {
    id: "s009",
    name: "Besan (Chickpea Flour)",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel",
    price: 4.99,
    unit: "2 lb",
    rank: 9,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Use for pakoras and kadhi",
    description: "Fine chickpea flour",
  },
  {
    id: "s010",
    name: "Parle-G Biscuits",
    categorySlug: "south-asian",
    section: "Snacks & Sweets",
    source: "patel",
    price: 2.49,
    unit: "3.17 oz",
    rank: 10,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Classic tea-time biscuit",
    description: "Original Parle-G glucose biscuits",
  },
  {
    id: "s011",
    name: "Haldiram's Bhujia",
    categorySlug: "south-asian",
    section: "Snacks & Sweets",
    source: "patel",
    price: 3.99,
    unit: "14 oz",
    rank: 11,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Crispy chickpea flour noodles",
    description: "Classic Indian namkeen",
  },
  {
    id: "s012",
    name: "Ghee (Pure Clarified Butter)",
    categorySlug: "south-asian",
    section: "Oils & Ghee",
    source: "patel",
    price: 12.99,
    unit: "16 oz",
    rank: 12,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Essential for authentic Indian cooking",
    description: "Pure desi ghee",
  },
  {
    id: "s013",
    name: "Mustard Oil",
    categorySlug: "south-asian",
    section: "Oils & Ghee",
    source: "patel",
    price: 7.99,
    unit: "16.9 oz",
    rank: 13,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Traditional cooking oil for pickles",
    description: "Pure mustard oil",
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products
    .filter((p) => p.categorySlug === categorySlug)
    .sort((a, b) => a.rank - b.rank);
}

export function getProductsBySection(
  categorySlug: string,
  section: string
): Product[] {
  return products
    .filter((p) => p.categorySlug === categorySlug && p.section === section)
    .sort((a, b) => a.rank - b.rank);
}

export function getProductsByCorner(cornerSlug: string): Product[] {
  return products
    .filter((p) => p.isCornerItem && p.cornerSlug === cornerSlug)
    .sort((a, b) => a.rank - b.rank);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getCornerBySlug(slug: string): Corner | undefined {
  return corners.find((c) => c.slug === slug);
}
