import { Product, Category, Corner } from "./types";

export const categories: Category[] = [
  {
    slug: "fresh-daily",
    name: "Fresh & Daily",
    icon: "Apple",
    sections: ["Produce", "Dairy", "Eggs", "Bakery"],
  },
  {
    slug: "smart-deals",
    name: "Smart Deals",
    icon: "Sparkles",
    sections: ["Weekly Specials", "Clearance", "Bulk Savings"],
  },
  {
    slug: "south-asian",
    name: "South Asian Essentials",
    icon: "Star",
    sections: [
      "Lentils & Pulses",
      "Rice & Grains",
      "Spices & Masalas",
      "Flours & Atta",
      "Snacks & Sweets",
      "Oils & Ghee",
    ],
  },
  {
    slug: "ready-to-cook",
    name: "Ready to Cook",
    icon: "ChefHat",
    sections: ["Frozen Breads", "Frozen Snacks", "Frozen Meals", "Frozen Desserts", "Frozen Veggies"],
  },
  {
    slug: "global-grocers",
    name: "Global Grocers",
    icon: "Globe",
    sections: ["Asian", "Mediterranean", "Latin American", "European"],
  },
  {
    slug: "pantry-staples",
    name: "Pantry Staples",
    icon: "Package",
    sections: ["Canned Goods", "Pasta", "Sauces", "Condiments"],
  },
  {
    slug: "beverages",
    name: "Beverages",
    icon: "Coffee",
    sections: ["Tea & Coffee", "Juices", "Soft Drinks", "Water"],
  },
];

export const corners: Corner[] = [
  {
    slug: "patel-brothers",
    name: "Patel Brothers Corner",
    categorySlug: "south-asian",
    description: "Curated South Asian essentials",
    badge: "Patel Brothers",
    sections: [
      "Lentils & Pulses",
      "Rice & Grains",
      "Spices & Masalas",
      "Flours & Atta",
      "Snacks & Sweets",
      "Oils & Ghee",
    ],
  },
  {
    slug: "shoprite",
    name: "ShopRite Corner",
    categorySlug: "fresh-daily",
    description: "Fresh produce and daily essentials",
    badge: "ShopRite",
    sections: ["Produce", "Dairy", "Bakery"],
  },
  {
    slug: "hmart",
    name: "H-Mart Corner",
    categorySlug: "global-grocers",
    description: "Asian specialty items",
    badge: "H-Mart",
    sections: ["Asian"],
  },
];

export const products: Product[] = [
  // Produce (Fresh & Daily)
  {
    id: "p001",
    name: "Bananas (Organic)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 0.99,
    unit: "lb",
    rank: 1,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for smoothies or breakfast bowls",
    aiSubstituteIds: ["p002"],
    description: "Fresh organic bananas, rich in potassium",
  },
  {
    id: "p002",
    name: "Plantains",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "local",
    price: 1.29,
    unit: "lb",
    rank: 2,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Great for frying or baking",
    description: "Fresh plantains for cooking",
  },
  {
    id: "p003",
    name: "Avocados (Hass)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "shoprite",
    price: 1.49,
    unit: "each",
    rank: 3,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Pair with lime and salt for guacamole",
    description: "Ripe Hass avocados",
  },
  {
    id: "p004",
    name: "Red Onions",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 1.99,
    unit: "3 lb bag",
    rank: 4,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Essential for curries and salads",
    description: "Fresh red onions",
  },
  {
    id: "p005",
    name: "Roma Tomatoes",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "shoprite",
    price: 2.49,
    unit: "lb",
    rank: 5,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for sauces and salsas",
    description: "Fresh Roma tomatoes",
  },
  {
    id: "p006",
    name: "Cilantro (Fresh Bunch)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 0.99,
    unit: "bunch",
    rank: 6,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Essential garnish for curries and tacos",
    description: "Fresh cilantro bunch",
  },
  {
    id: "p007",
    name: "English Cucumbers",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 1.99,
    unit: "each",
    rank: 7,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Great for salads and raita",
    description: "Seedless English cucumbers",
  },

  // Frozen (Ready to Cook) - Indian Grocery Items
  {
    id: "f001",
    name: "Frozen Paratha (Plain)",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel",
    price: 5.99,
    unit: "20 count",
    rank: 1,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Heat and serve with curry or pickle",
    description: "Authentic frozen plain parathas",
  },
  {
    id: "f002",
    name: "Frozen Aloo Paratha",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel",
    price: 6.49,
    unit: "16 count",
    rank: 2,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Serve with yogurt and pickle",
    description: "Potato-stuffed parathas",
  },
  {
    id: "f003",
    name: "Frozen Gobi Paratha",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel",
    price: 6.49,
    unit: "16 count",
    rank: 3,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Cauliflower stuffed, serve with raita",
    description: "Cauliflower-stuffed parathas",
  },
  {
    id: "f004",
    name: "Frozen Methi Paratha",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel",
    price: 6.99,
    unit: "12 count",
    rank: 4,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Fenugreek flavored, great with dal",
    description: "Fenugreek parathas",
  },
  {
    id: "f005",
    name: "Frozen Chapati",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel",
    price: 4.99,
    unit: "30 count",
    rank: 5,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Quick roti for any meal",
    description: "Ready-to-heat chapatis",
  },
  {
    id: "f006",
    name: "Frozen Samosas (Veg)",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel",
    price: 6.99,
    unit: "20 count",
    rank: 6,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Fry or bake until golden",
    description: "Spiced potato samosas",
  },
  {
    id: "f007",
    name: "Frozen Onion Bhaji",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel",
    price: 5.99,
    unit: "15 count",
    rank: 7,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Crispy onion fritters, serve with chutney",
    description: "Crispy onion bhajis",
  },
  {
    id: "f008",
    name: "Frozen Aloo Tikki",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel",
    price: 5.49,
    unit: "12 count",
    rank: 8,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Pan fry and top with chutneys",
    description: "Spiced potato patties",
  },
  {
    id: "f009",
    name: "Frozen Pakoras (Mixed)",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel",
    price: 6.49,
    unit: "24 count",
    rank: 9,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Deep fry for chai time snack",
    description: "Assorted vegetable pakoras",
  },
  {
    id: "f010",
    name: "Frozen Kachori",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel",
    price: 7.49,
    unit: "10 count",
    rank: 10,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Crispy dal-stuffed pastry",
    description: "Dal-stuffed kachoris",
  },
  {
    id: "f011",
    name: "Frozen Paneer Tikka",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 9.99,
    unit: "16 oz",
    rank: 11,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Grill or pan-fry, serve with naan",
    description: "Marinated paneer tikka",
  },
  {
    id: "f012",
    name: "Frozen Dal Makhani",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 7.99,
    unit: "16 oz",
    rank: 12,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Heat and serve with rice or naan",
    description: "Creamy black lentil curry",
  },
  {
    id: "f013",
    name: "Frozen Palak Paneer",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 8.49,
    unit: "16 oz",
    rank: 13,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Spinach and cottage cheese curry",
    description: "Palak paneer ready meal",
  },
  {
    id: "f014",
    name: "Frozen Chana Masala",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 6.99,
    unit: "16 oz",
    rank: 14,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Serve with bhatura or rice",
    description: "Spiced chickpea curry",
  },
  {
    id: "f015",
    name: "Frozen Vegetable Biryani",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel",
    price: 8.99,
    unit: "24 oz",
    rank: 15,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Aromatic rice with vegetables",
    description: "Ready-to-heat veg biryani",
  },
  {
    id: "f016",
    name: "Mango Kulfi",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel",
    price: 7.99,
    unit: "12 count",
    rank: 16,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Traditional Indian frozen dessert",
    description: "Authentic mango kulfi bars",
  },
  {
    id: "f017",
    name: "Malai Kulfi",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel",
    price: 7.99,
    unit: "12 count",
    rank: 17,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Creamy cardamom kulfi",
    description: "Traditional malai kulfi bars",
  },
  {
    id: "f018",
    name: "Pista Kulfi",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel",
    price: 8.49,
    unit: "12 count",
    rank: 18,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Pistachio flavored kulfi",
    description: "Premium pista kulfi bars",
  },
  {
    id: "f019",
    name: "Frozen Gulab Jamun",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel",
    price: 6.99,
    unit: "16 count",
    rank: 19,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Heat and serve in warm syrup",
    description: "Sweet milk dumplings",
  },
  {
    id: "f020",
    name: "Frozen Rasmalai",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel",
    price: 8.99,
    unit: "12 count",
    rank: 20,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Thaw and serve chilled",
    description: "Cottage cheese in sweet cream",
  },
  {
    id: "f021",
    name: "Frozen Green Peas",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel",
    price: 3.49,
    unit: "2 lb",
    rank: 21,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Add to pulao, matar paneer",
    description: "Premium frozen green peas",
  },
  {
    id: "f022",
    name: "Frozen Methi Leaves",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel",
    price: 4.49,
    unit: "14 oz",
    rank: 22,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Perfect for methi dishes",
    description: "Frozen fenugreek leaves",
  },
  {
    id: "f023",
    name: "Frozen Palak (Spinach)",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel",
    price: 3.99,
    unit: "16 oz",
    rank: 23,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Ready for palak paneer or dal",
    description: "Chopped frozen spinach",
  },
  {
    id: "f024",
    name: "Frozen Mixed Vegetables",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel",
    price: 4.99,
    unit: "2 lb",
    rank: 24,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    isFrozen: true,
    aiPairingText: "Carrots, beans, peas blend",
    description: "Indian-style mixed vegetables",
  },

  // South Asian Essentials
  {
    id: "s001",
    name: "Toor Dal (Split Pigeon Peas)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel",
    price: 4.99,
    unit: "2 lb",
    rank: 1,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Perfect for dal tadka and sambar",
    aiSubstituteIds: ["s002"],
    description: "Premium quality toor dal",
  },
  {
    id: "s002",
    name: "Chana Dal (Split Chickpeas)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel",
    price: 3.99,
    unit: "2 lb",
    rank: 2,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Great for chana dal fry or halwa",
    description: "Premium chana dal",
  },
  {
    id: "s003",
    name: "Moong Dal (Split Mung Beans)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel",
    price: 4.49,
    unit: "2 lb",
    rank: 3,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Light and nutritious dal",
    description: "Yellow moong dal",
  },
  {
    id: "s004",
    name: "Basmati Rice (Aged)",
    categorySlug: "south-asian",
    section: "Rice & Grains",
    source: "patel",
    price: 19.99,
    unit: "10 lb",
    rank: 4,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Perfect for biryani and pulao",
    description: "Premium aged basmati rice",
  },
  {
    id: "s005",
    name: "Turmeric Powder (Haldi)",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel",
    price: 3.99,
    unit: "7 oz",
    rank: 5,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Essential spice for curries",
    description: "Pure turmeric powder",
  },
  {
    id: "s006",
    name: "Cumin Seeds (Jeera)",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel",
    price: 2.99,
    unit: "3.5 oz",
    rank: 6,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Great for tempering dals",
    description: "Whole cumin seeds",
  },
  {
    id: "s007",
    name: "Garam Masala",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel",
    price: 4.49,
    unit: "3.5 oz",
    rank: 7,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Finishing touch for curries",
    description: "Authentic garam masala blend",
  },
  {
    id: "s008",
    name: "Chakki Atta (Whole Wheat Flour)",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel",
    price: 8.99,
    unit: "10 lb",
    rank: 8,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Perfect for rotis and parathas",
    description: "Stone-ground whole wheat flour",
  },
  {
    id: "s009",
    name: "Besan (Chickpea Flour)",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel",
    price: 4.99,
    unit: "2 lb",
    rank: 9,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Use for pakoras and kadhi",
    description: "Fine chickpea flour",
  },
  {
    id: "s010",
    name: "Parle-G Biscuits",
    categorySlug: "south-asian",
    section: "Snacks & Sweets",
    source: "patel",
    price: 2.49,
    unit: "3.17 oz",
    rank: 10,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Classic tea-time biscuit",
    description: "Original Parle-G glucose biscuits",
  },
  {
    id: "s011",
    name: "Haldiram's Bhujia",
    categorySlug: "south-asian",
    section: "Snacks & Sweets",
    source: "patel",
    price: 3.99,
    unit: "14 oz",
    rank: 11,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Crispy chickpea flour noodles",
    description: "Classic Indian namkeen",
  },
  {
    id: "s012",
    name: "Ghee (Pure Clarified Butter)",
    categorySlug: "south-asian",
    section: "Oils & Ghee",
    source: "patel",
    price: 12.99,
    unit: "16 oz",
    rank: 12,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Essential for authentic Indian cooking",
    description: "Pure desi ghee",
  },
  {
    id: "s013",
    name: "Mustard Oil",
    categorySlug: "south-asian",
    section: "Oils & Ghee",
    source: "patel",
    price: 7.99,
    unit: "16.9 oz",
    rank: 13,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "patel-brothers",
    aiPairingText: "Traditional cooking oil for pickles",
    description: "Pure mustard oil",
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products
    .filter((p) => p.categorySlug === categorySlug)
    .sort((a, b) => a.rank - b.rank);
}

export function getProductsBySection(
  categorySlug: string,
  section: string
): Product[] {
  return products
    .filter((p) => p.categorySlug === categorySlug && p.section === section)
    .sort((a, b) => a.rank - b.rank);
}

export function getProductsByCorner(cornerSlug: string): Product[] {
  return products
    .filter((p) => p.isCornerItem && p.cornerSlug === cornerSlug)
    .sort((a, b) => a.rank - b.rank);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getCornerBySlug(slug: string): Corner | undefined {
  return corners.find((c) => c.slug === slug);
}
