import { Product, Category, Corner } from "./types";

export const categories: Category[] = [
  {
    slug: "fresh-daily",
    name: "Fresh & Daily",
    icon: "Apple",
    sections: ["Produce", "Dairy", "Eggs", "Bakery"],
  },
  {
    slug: "smart-deals",
    name: "Smart Deals",
    icon: "Sparkles",
    sections: ["Weekly Specials", "Clearance", "Bulk Savings"],
  },
  {
    slug: "south-asian",
    name: "South Asian Essentials",
    icon: "Star",
    sections: [
      "Lentils & Pulses",
      "Rice & Grains",
      "Spices & Masalas",
      "Flours & Atta",
      "Snacks & Sweets",
      "Oils & Ghee",
    ],
  },
  {
    slug: "ready-to-cook",
    name: "Ready to Cook",
    icon: "ChefHat",
    sections: ["Frozen Breads", "Frozen Snacks", "Frozen Meals", "Frozen Desserts", "Frozen Veggies"],
  },
  {
    slug: "global-grocers",
    name: "Global Grocers",
    icon: "Globe",
    sections: ["Asian", "Mediterranean", "Latin American", "European"],
  },
  {
    slug: "pantry-staples",
    name: "Pantry Staples",
    icon: "Package",
    sections: ["Oils", "Condiments", "Baking", "Canned Goods", "Pasta", "Sauces"],
  },
  {
    slug: "beverages",
    name: "Beverages",
    icon: "Coffee",
    sections: ["Tea & Coffee", "Juices", "Soft Drinks", "Water"],
  },
];

export const corners: Corner[] = [
  {
    slug: "neomart-grocery",
    name: "NeoMart Grocery",
    categorySlug: "south-asian",
    description: "Curated South Asian essentials",
    badge: "NeoMart Grocery",
    sections: [
      "Lentils & Pulses",
      "Rice & Grains",
      "Spices & Masalas",
      "Flours & Atta",
      "Snacks & Sweets",
      "Oils & Ghee",
    ],
  },
];

export const products: Product[] = [
  // Produce (Fresh & Daily)
  {
    id: "p001",
    name: "Bananas (Organic)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 0.99,
    unit: "lb",
    rank: 1,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for smoothies or breakfast bowls",
    aiSubstituteIds: ["p002"],
    description: "Fresh organic bananas, rich in potassium",
    image: "/products/yellow_banana.png",
  },
  {
    id: "p002",
    name: "Plantains",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "local",
    price: 1.29,
    unit: "lb",
    rank: 2,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Great for frying or baking",
    description: "Fresh plantains for cooking",
    image: "/products/plantains.png",
  },
  {
    id: "p003",
    name: "Avocados (Hass)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "patel-brothers",
    price: 1.49,
    unit: "each",
    rank: 3,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Pair with lime and salt for guacamole",
    description: "Ripe Hass avocados",
    image: "/products/avocados.png",
  },
  {
    id: "p004",
    name: "Red Onions",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 1.99,
    unit: "3 lb bag",
    rank: 4,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Essential for curries and salads",
    description: "Fresh red onions",
    image: "/products/red_onion.png",
  },
  {
    id: "p005",
    name: "Roma Tomatoes",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "patel-brothers",
    price: 2.49,
    unit: "lb",
    rank: 5,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for sauces and salsas",
    description: "Fresh Roma tomatoes",
    image: "/products/roma_tomatoes.png",
  },
  {
    id: "p006",
    name: "Cilantro (Fresh Bunch)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 0.99,
    unit: "bunch",
    rank: 6,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Essential garnish for curries and tacos",
    description: "Fresh cilantro bunch",
    image: "/products/coriander.png",
  },
  {
    id: "p007",
    name: "English Cucumbers",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "patel-brothers",
    price: 1.99,
    unit: "each",
    rank: 7,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Great for salads and raita",
    description: "Seedless English cucumbers",
    image: "/products/english_cucumbers.png",
  },
  {
    id: "p008",
    name: "Fresh Broccoli",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 2.99,
    unit: "lb",
    rank: 8,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Steam or roast for healthy side dish",
    description: "Fresh green broccoli florets",
    image: "/products/broccoli.png",
  },
  {
    id: "p009",
    name: "Fresh Cauliflower",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 3.49,
    unit: "each",
    rank: 9,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for aloo gobi and roasting",
    description: "Fresh white cauliflower head",
    image: "/products/cauliflower.png",
  },
  {
    id: "p010",
    name: "Fresh Lemons",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 0.79,
    unit: "each",
    rank: 10,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Essential for drinks and marinades",
    description: "Fresh juicy lemons",
    image: "/products/lemon.png",
  },
  {
    id: "p011",
    name: "Fresh Mint Leaves",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 1.49,
    unit: "bunch",
    rank: 11,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Great for chutney and mojitos",
    description: "Fresh aromatic mint leaves",
    image: "/products/mint_leaves.png",
  },
  {
    id: "p012",
    name: "Fresh Okra (Bhindi)",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "patel-brothers",
    price: 2.99,
    unit: "lb",
    rank: 12,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for bhindi masala",
    description: "Fresh tender okra pods",
    image: "/products/okra.png",
  },
  {
    id: "p013",
    name: "Red Apples",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 1.99,
    unit: "lb",
    rank: 13,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Crispy and sweet for snacking",
    description: "Fresh crisp red apples",
    image: "/products/red_apple.png",
  },
  {
    id: "p014",
    name: "Fresh Strawberries",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "neomart",
    price: 4.99,
    unit: "16 oz container",
    rank: 14,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Perfect for desserts and smoothies",
    description: "Sweet ripe strawberries",
    image: "/products/strawberries.png",
  },
  {
    id: "p015",
    name: "Fresh Lychee",
    categorySlug: "fresh-daily",
    section: "Produce",
    source: "patel-brothers",
    price: 5.99,
    unit: "lb",
    rank: 15,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    isProduce: true,
    aiPairingText: "Sweet tropical fruit for desserts",
    description: "Fresh sweet lychee",
    image: "/products/lychee.png",
  },
  {
    id: "d001",
    name: "Whole Milk Gallon",
    categorySlug: "fresh-daily",
    section: "Dairy",
    source: "neomart",
    price: 4.99,
    unit: "1 gallon",
    rank: 1,
    dietaryTags: [],
    isCornerItem: false,
    aiPairingText: "Fresh dairy for your family",
    description: "Fresh whole milk",
    image: "/products/milk_gallon.png",
  },
  {
    id: "d002",
    name: "Paneer (Indian Cottage Cheese)",
    categorySlug: "fresh-daily",
    section: "Dairy",
    source: "patel-brothers",
    price: 6.99,
    unit: "14 oz",
    rank: 2,
    dietaryTags: ["veg"],
    isCornerItem: false,
    aiPairingText: "Perfect for paneer tikka and curries",
    description: "Fresh homemade-style paneer",
    image: "/products/swad_paneer.png",
  },

  // Frozen (Ready to Cook) - Indian Grocery Items
  {
    id: "f001",
    name: "Frozen Paratha (Plain)",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "neomart",
    price: 5.99,
    unit: "20 count",
    rank: 1,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Heat and serve with curry or pickle",
    description: "Authentic frozen plain parathas",
    image: "/products/kawan_plain_paratha.png",
  },
  {
    id: "f002",
    name: "Frozen Aloo Paratha",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel-brothers",
    price: 6.49,
    unit: "16 count",
    rank: 2,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Serve with yogurt and pickle",
    description: "Potato-stuffed parathas",
    image: "/products/frozen_aloo_paratha.png",
  },
  {
    id: "f003",
    name: "Frozen Gobi Paratha",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel-brothers",
    price: 6.49,
    unit: "16 count",
    rank: 3,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Cauliflower stuffed, serve with raita",
    description: "Cauliflower-stuffed parathas",
  },
  {
    id: "f004",
    name: "Frozen Methi Paratha",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel-brothers",
    price: 6.99,
    unit: "12 count",
    rank: 4,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Fenugreek flavored, great with dal",
    description: "Fenugreek parathas",
  },
  {
    id: "f005",
    name: "Frozen Chapati",
    categorySlug: "ready-to-cook",
    section: "Frozen Breads",
    source: "patel-brothers",
    price: 4.99,
    unit: "30 count",
    rank: 5,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Quick roti for any meal",
    description: "Ready-to-heat chapatis",
  },
  {
    id: "f006",
    name: "Frozen Samosas (Veg)",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel-brothers",
    price: 6.99,
    unit: "20 count",
    rank: 6,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Fry or bake until golden",
    description: "Spiced potato samosas",
  },
  {
    id: "f007",
    name: "Frozen Onion Bhaji",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel-brothers",
    price: 5.99,
    unit: "15 count",
    rank: 7,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Crispy onion fritters, serve with chutney",
    description: "Crispy onion bhajis",
  },
  {
    id: "f008",
    name: "Frozen Aloo Tikki",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel-brothers",
    price: 5.49,
    unit: "12 count",
    rank: 8,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Pan fry and top with chutneys",
    description: "Spiced potato patties",
  },
  {
    id: "f009",
    name: "Frozen Pakoras (Mixed)",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel-brothers",
    price: 6.49,
    unit: "24 count",
    rank: 9,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Deep fry for chai time snack",
    description: "Assorted vegetable pakoras",
  },
  {
    id: "f010",
    name: "Frozen Kachori",
    categorySlug: "ready-to-cook",
    section: "Frozen Snacks",
    source: "patel-brothers",
    price: 7.49,
    unit: "10 count",
    rank: 10,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Crispy dal-stuffed pastry",
    description: "Dal-stuffed kachoris",
  },
  {
    id: "f011",
    name: "Frozen Paneer Tikka",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel-brothers",
    price: 9.99,
    unit: "16 oz",
    rank: 11,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Grill or pan-fry, serve with naan",
    description: "Marinated paneer tikka",
  },
  {
    id: "f012",
    name: "Frozen Dal Makhani",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel-brothers",
    price: 7.99,
    unit: "16 oz",
    rank: 12,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Heat and serve with rice or naan",
    description: "Creamy black lentil curry",
  },
  {
    id: "f013",
    name: "Frozen Palak Paneer",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel-brothers",
    price: 8.49,
    unit: "16 oz",
    rank: 13,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Spinach and cottage cheese curry",
    description: "Palak paneer ready meal",
  },
  {
    id: "f014",
    name: "Frozen Chana Masala",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel-brothers",
    price: 6.99,
    unit: "16 oz",
    rank: 14,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Serve with bhatura or rice",
    description: "Spiced chickpea curry",
  },
  {
    id: "f015",
    name: "Frozen Vegetable Biryani",
    categorySlug: "ready-to-cook",
    section: "Frozen Meals",
    source: "patel-brothers",
    price: 8.99,
    unit: "24 oz",
    rank: 15,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Aromatic rice with vegetables",
    description: "Ready-to-heat veg biryani",
  },
  {
    id: "f016",
    name: "Mango Kulfi",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel-brothers",
    price: 7.99,
    unit: "12 count",
    rank: 16,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Traditional Indian frozen dessert",
    description: "Authentic mango kulfi bars",
  },
  {
    id: "f017",
    name: "Malai Kulfi",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel-brothers",
    price: 7.99,
    unit: "12 count",
    rank: 17,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Creamy cardamom kulfi",
    description: "Traditional malai kulfi bars",
    image: "/products/vadilal_classic_malai_kulfi.png",
  },
  {
    id: "f018",
    name: "Pista Kulfi",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel-brothers",
    price: 8.49,
    unit: "12 count",
    rank: 18,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Pistachio flavored kulfi",
    description: "Premium pista kulfi bars",
  },
  {
    id: "f019",
    name: "Frozen Gulab Jamun",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel-brothers",
    price: 6.99,
    unit: "16 count",
    rank: 19,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Heat and serve in warm syrup",
    description: "Sweet milk dumplings",
    image: "/products/nanak_gulabjamun.png",
  },
  {
    id: "f020",
    name: "Frozen Rasmalai",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel-brothers",
    price: 8.99,
    unit: "12 count",
    rank: 20,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Thaw and serve chilled",
    description: "Cottage cheese in sweet cream",
  },
  {
    id: "f021",
    name: "Frozen Green Peas",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel-brothers",
    price: 3.49,
    unit: "2 lb",
    rank: 21,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Add to pulao, matar paneer",
    description: "Premium frozen green peas",
  },
  {
    id: "f022",
    name: "Frozen Methi Leaves",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel-brothers",
    price: 4.49,
    unit: "14 oz",
    rank: 22,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Perfect for methi dishes",
    description: "Frozen fenugreek leaves",
  },
  {
    id: "f023",
    name: "Frozen Palak (Spinach)",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel-brothers",
    price: 3.99,
    unit: "16 oz",
    rank: 23,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Ready for palak paneer or dal",
    description: "Chopped frozen spinach",
  },
  {
    id: "f024",
    name: "Frozen Mixed Vegetables",
    categorySlug: "ready-to-cook",
    section: "Frozen Veggies",
    source: "patel-brothers",
    price: 4.99,
    unit: "2 lb",
    rank: 24,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    isFrozen: true,
    aiPairingText: "Carrots, beans, peas blend",
    description: "Indian-style mixed vegetables",
  },
  {
    id: "f025",
    name: "Vadilal Vanilla Ice Cream",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "patel-brothers",
    price: 8.99,
    unit: "1 quart",
    rank: 25,
    dietaryTags: ["veg"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Classic creamy vanilla ice cream",
    description: "Premium vanilla ice cream",
    image: "/products/vadilal_vanilla_ice_cream.png",
  },
  {
    id: "f026",
    name: "Vanilla Sandwich Ice Cream",
    categorySlug: "ready-to-cook",
    section: "Frozen Desserts",
    source: "neomart",
    price: 5.99,
    unit: "12 count",
    rank: 26,
    dietaryTags: ["veg"],
    isCornerItem: false,
    isFrozen: true,
    aiPairingText: "Classic ice cream sandwich treat",
    description: "Vanilla ice cream between cookies",
    image: "/products/vanilla_sandwich_ice_cream.png",
  },

  // South Asian Essentials
  {
    id: "s001",
    name: "Toor Dal (Split Pigeon Peas)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "neomart",
    price: 4.99,
    unit: "2 lb",
    rank: 1,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Perfect for dal tadka and sambar",
    aiSubstituteIds: ["s002"],
    description: "Premium quality toor dal",
  },
  {
    id: "s002",
    name: "Chana Dal (Split Chickpeas)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel-brothers",
    price: 3.99,
    unit: "2 lb",
    rank: 2,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Great for chana dal fry or halwa",
    description: "Premium chana dal",
  },
  {
    id: "s003",
    name: "Moong Dal (Split Mung Beans)",
    categorySlug: "south-asian",
    section: "Lentils & Pulses",
    source: "patel-brothers",
    price: 4.49,
    unit: "2 lb",
    rank: 3,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Light and nutritious dal",
    description: "Yellow moong dal",
    image: "/products/swad_moong_whole.png",
  },
  {
    id: "s004",
    name: "Basmati Rice (Aged)",
    categorySlug: "south-asian",
    section: "Rice & Grains",
    source: "patel-brothers",
    price: 19.99,
    unit: "10 lb",
    rank: 4,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Perfect for biryani and pulao",
    description: "Premium aged basmati rice",
    image: "/products/royal_basmati_rice_20lb.png",
  },
  {
    id: "s004a",
    name: "Sona Masoori Rice",
    categorySlug: "south-asian",
    section: "Rice & Grains",
    source: "patel-brothers",
    price: 24.99,
    unit: "20 lb",
    rank: 5,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Light and fluffy rice for daily meals",
    description: "Premium Sona Masoori rice",
    image: "/products/raja_foods_sona_masoori_rice.png",
  },
  {
    id: "s004b",
    name: "Crystal Sona Masoori Rice",
    categorySlug: "south-asian",
    section: "Rice & Grains",
    source: "patel-brothers",
    price: 22.99,
    unit: "20 lb",
    rank: 6,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Premium quality South Indian rice",
    description: "Crystal Sona Masoori rice",
    image: "/products/swad_crystal_sona_masoori_rice.png",
  },
  {
    id: "s004c",
    name: "Ambe Mohar Rice",
    categorySlug: "south-asian",
    section: "Rice & Grains",
    source: "patel-brothers",
    price: 18.99,
    unit: "10 lb",
    rank: 7,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Aromatic everyday rice",
    description: "Ambe Mohar premium rice",
    image: "/products/swad_ambe_mohar_rice.png",
  },
  {
    id: "s004d",
    name: "Bajra Millet",
    categorySlug: "south-asian",
    section: "Rice & Grains",
    source: "patel-brothers",
    price: 5.99,
    unit: "2 lb",
    rank: 8,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Healthy millet for rotis and porridge",
    description: "Pearl millet (Bajra)",
    image: "/products/manna_bajra_millet.png",
  },
  {
    id: "s005",
    name: "Turmeric Powder (Haldi)",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel-brothers",
    price: 3.99,
    unit: "7 oz",
    rank: 9,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Essential spice for curries",
    description: "Pure turmeric powder",
  },
  {
    id: "s005a",
    name: "Everest Chaat Masala",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel-brothers",
    price: 4.49,
    unit: "3.5 oz",
    rank: 10,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Tangy spice blend for snacks",
    description: "Authentic chaat masala",
    image: "/products/everest_chaat_masala.png",
  },
  {
    id: "s005b",
    name: "Everest Pav Bhaji Masala",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel-brothers",
    price: 4.49,
    unit: "3.5 oz",
    rank: 11,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Perfect spice blend for pav bhaji",
    description: "Authentic pav bhaji masala",
    image: "/products/everest_pav_bhaji_masala.png",
  },
  {
    id: "s006",
    name: "Cumin Seeds (Jeera)",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel-brothers",
    price: 2.99,
    unit: "3.5 oz",
    rank: 12,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Great for tempering dals",
    description: "Whole cumin seeds",
  },
  {
    id: "s007",
    name: "Garam Masala",
    categorySlug: "south-asian",
    section: "Spices & Masalas",
    source: "patel-brothers",
    price: 4.49,
    unit: "3.5 oz",
    rank: 13,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Finishing touch for curries",
    description: "Authentic garam masala blend",
  },
  {
    id: "s008",
    name: "Chakki Atta (Whole Wheat Flour)",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel-brothers",
    price: 8.99,
    unit: "10 lb",
    rank: 14,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Perfect for rotis and parathas",
    description: "Stone-ground whole wheat flour",
    image: "/products/swad_chakki_atta.png",
  },
  {
    id: "s008a",
    name: "Multigrain Atta",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel-brothers",
    price: 9.99,
    unit: "10 lb",
    rank: 15,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Healthy blend for nutritious rotis",
    description: "Multi-grain wheat flour",
    image: "/products/aashirvaad_atta_multigrains.png",
  },
  {
    id: "s008b",
    name: "Whole Wheat Rotika",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel-brothers",
    price: 7.99,
    unit: "10 lb",
    rank: 16,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Fresh rotis made easy",
    description: "Whole wheat rotika flour",
    image: "/products/rotika_whole_wheat.png",
  },
  {
    id: "s009",
    name: "Besan (Chickpea Flour)",
    categorySlug: "south-asian",
    section: "Flours & Atta",
    source: "patel-brothers",
    price: 4.99,
    unit: "2 lb",
    rank: 17,
    dietaryTags: ["veg", "vegan", "gluten-free"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Use for pakoras and kadhi",
    description: "Fine chickpea flour",
  },
  {
    id: "s010",
    name: "Parle-G Biscuits",
    categorySlug: "south-asian",
    section: "Snacks & Sweets",
    source: "patel-brothers",
    price: 2.49,
    unit: "3.17 oz",
    rank: 18,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Classic tea-time biscuit",
    description: "Original Parle-G glucose biscuits",
  },
  {
    id: "s011",
    name: "Haldiram's Bhujia",
    categorySlug: "south-asian",
    section: "Snacks & Sweets",
    source: "patel-brothers",
    price: 3.99,
    unit: "14 oz",
    rank: 19,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Crispy chickpea flour noodles",
    description: "Classic Indian namkeen",
  },
  {
    id: "s011a",
    name: "Garvi Gujarat Gathiya",
    categorySlug: "south-asian",
    section: "Snacks & Sweets",
    source: "patel-brothers",
    price: 4.49,
    unit: "10 oz",
    rank: 20,
    dietaryTags: ["veg"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Crunchy Gujarati snack",
    description: "Authentic gathiya",
    image: "/products/garvi_gujarat_gathiya.png",
  },
  {
    id: "s012",
    name: "Ghee (Pure Clarified Butter)",
    categorySlug: "south-asian",
    section: "Oils & Ghee",
    source: "patel-brothers",
    price: 12.99,
    unit: "16 oz",
    rank: 21,
    dietaryTags: [],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Essential for authentic Indian cooking",
    description: "Pure desi ghee",
    image: "/products/swad_ghee.png",
  },
  {
    id: "s013",
    name: "Mustard Oil (KTC)",
    categorySlug: "south-asian",
    section: "Oils & Ghee",
    source: "patel-brothers",
    price: 7.99,
    unit: "16.9 oz",
    rank: 22,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Traditional cooking oil for pickles",
    description: "Pure mustard oil",
    image: "/products/ktc_mustard_oil.png",
  },
  {
    id: "s013a",
    name: "Mustard Oil (Laxmi)",
    categorySlug: "south-asian",
    section: "Oils & Ghee",
    source: "patel-brothers",
    price: 8.49,
    unit: "16.9 oz",
    rank: 23,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: true,
    cornerSlug: "neomart-grocery",
    aiPairingText: "Premium cooking oil",
    description: "Pure Laxmi mustard oil",
    image: "/products/laxmi_mustard_oil.png",
  },
  {
    id: "s013b",
    name: "Avocado Oil",
    categorySlug: "pantry-staples",
    section: "Oils",
    source: "neomart",
    price: 11.99,
    unit: "16.9 oz",
    rank: 1,
    dietaryTags: ["veg", "vegan", "organic"],
    isCornerItem: false,
    aiPairingText: "Healthy oil for cooking and salads",
    description: "Premium avocado oil",
    image: "/products/ios_avocado_oil.png",
  },
  {
    id: "pan001",
    name: "Grated Coconut (Frozen)",
    categorySlug: "pantry-staples",
    section: "Condiments",
    source: "neomart",
    price: 4.99,
    unit: "14 oz",
    rank: 2,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    aiPairingText: "Ready-to-use grated coconut",
    description: "Frozen grated coconut",
    image: "/products/swad_grated_coconut.png",
  },
  {
    id: "pan002",
    name: "Kesar Mango Pulp",
    categorySlug: "pantry-staples",
    section: "Condiments",
    source: "neomart",
    price: 5.99,
    unit: "30 oz",
    rank: 3,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    aiPairingText: "Perfect for mango lassi and desserts",
    description: "Kesar mango pulp",
    image: "/products/swad_kesar_mango_pulp.png",
  },
  {
    id: "pan003",
    name: "Delhi Ki Chaat Chutney",
    categorySlug: "pantry-staples",
    section: "Condiments",
    source: "neomart",
    price: 3.99,
    unit: "7.8 oz",
    rank: 4,
    dietaryTags: ["veg"],
    isCornerItem: false,
    aiPairingText: "Authentic street food flavor",
    description: "Sweet and tangy chaat chutney",
    image: "/products/swad_chutneys_delhi_ki_chaat.png",
  },
  {
    id: "pan004",
    name: "Pani Puri Concentrate",
    categorySlug: "pantry-staples",
    section: "Condiments",
    source: "neomart",
    price: 3.99,
    unit: "7.8 oz",
    rank: 5,
    dietaryTags: ["veg"],
    isCornerItem: false,
    aiPairingText: "Make pani puri water instantly",
    description: "Pani puri concentrate",
    image: "/products/swad_chutneys_pani_puri_concentrate.png",
  },
  {
    id: "pan005",
    name: "Arm & Hammer Baking Soda",
    categorySlug: "pantry-staples",
    section: "Baking",
    source: "neomart",
    price: 1.99,
    unit: "1 lb",
    rank: 6,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    aiPairingText: "Essential for baking and cleaning",
    description: "Pure baking soda",
    image: "/products/arm_and_hammer_baking_soda.png",
  },
  {
    id: "bev001",
    name: "Tata Tea Gold",
    categorySlug: "beverages",
    section: "Tea & Coffee",
    source: "neomart",
    price: 12.99,
    unit: "500g",
    rank: 1,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    aiPairingText: "Premium Indian black tea",
    description: "Tata Tea Gold",
    image: "/products/tata_tea_gold_500g.png",
  },
  {
    id: "bev002",
    name: "Wagh Bakri Tea",
    categorySlug: "beverages",
    section: "Tea & Coffee",
    source: "neomart",
    price: 11.99,
    unit: "1 lb",
    rank: 2,
    dietaryTags: ["veg", "vegan"],
    isCornerItem: false,
    aiPairingText: "Traditional Indian chai",
    description: "Wagh Bakri premium tea",
    image: "/products/wagh_bakri_tea.png",
  },
  {
    id: "bev003",
    name: "Maaza Mango Juice",
    categorySlug: "beverages",
    section: "Juices",
    source: "neomart",
    price: 3.99,
    unit: "1.2 L",
    rank: 3,
    dietaryTags: ["veg"],
    isCornerItem: false,
    aiPairingText: "Refreshing mango drink",
    description: "Maaza mango juice drink",
    image: "/products/mazza_mango_juice.png",
  },
  {
    id: "bev004",
    name: "Tropicana Orange Juice",
    categorySlug: "beverages",
    section: "Juices",
    source: "neomart",
    price: 5.99,
    unit: "52 oz",
    rank: 4,
    dietaryTags: ["veg"],
    isCornerItem: false,
    aiPairingText: "100% pure orange juice",
    description: "Tropicana 100% orange juice",
    image: "/products/tropicana_100_orange_juice.png",
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products
    .filter((p) => p.categorySlug === categorySlug)
    .sort((a, b) => a.rank - b.rank);
}

export function getProductsBySection(
  categorySlug: string,
  section: string
): Product[] {
  return products
    .filter((p) => p.categorySlug === categorySlug && p.section === section)
    .sort((a, b) => a.rank - b.rank);
}

export function getProductsByCorner(cornerSlug: string): Product[] {
  return products
    .filter((p) => p.isCornerItem && p.cornerSlug === cornerSlug)
    .sort((a, b) => a.rank - b.rank);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getCornerBySlug(slug: string): Corner | undefined {
  return corners.find((c) => c.slug === slug);
}
